version: '3.8'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_test
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
